version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install flask pytest
  pre_build:
    commands:
      - echo "Applying code fix"
      - if [ -n "$CODE_FIX" ]; then eval "$CODE_FIX"; fi
      - git config --global user.name "Self-HealingCI"
      - git config --global user.email "selfhealing@example.com"
      - git add app.py
      - git commit -m "AI self-healing: Fix test failure" || true
      - git push https://$GITHUB_TOKEN@github.com/TATULIBOS1/self-healing-ci-cd-demo.git
  build:
    commands:
      - pytest -v
