name: AI-Powered Self-Healing CI/CD

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install flask pytest boto3

      - name: Run tests with detailed logging
        id: run-tests
        run: |
          # Generate JUnit XML for better test reporting
          pytest --junitxml=test-results.xml -v > test_logs.txt 2>&1 || true
          # Extract failure summary
          grep -E 'FAILED|ERROR' test_logs.txt > failure_summary.txt || echo "No failures detected"
        continue-on-error: true

      - name: Configure AWS Credentials
        if: failure()
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-duration-seconds: 900

      - name: Upload artifacts to S3
        if: failure()
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          aws s3 cp test_logs.txt s3://ci-cd-demo-logs/$GITHUB_RUN_ID/$TIMESTAMP/full_logs.txt
          aws s3 cp failure_summary.txt s3://ci-cd-demo-logs/$GITHUB_RUN_ID/$TIMESTAMP/failure_summary.txt
          aws s3 cp test-results.xml s3://ci-cd-demo-logs/$GITHUB_RUN_ID/$TIMESTAMP/test_results.xml

      - name: Trigger AI Analysis
        if: failure()
        env:
          S3_PREFIX: $GITHUB_RUN_ID/$TIMESTAMP
        run: |
          # Start Step Functions execution
          EXECUTION_NAME="github-$GITHUB_RUN_ID-$(date +%s)"
          RESPONSE=$(aws stepfunctions start-execution \
            --state-machine-arn ${{ secrets.SFN_SELF_HEALING_ARN }} \
            --name "$EXECUTION_NAME" \
            --input "{\"s3_bucket\":\"ci-cd-demo-logs\",\"s3_prefix\":\"$S3_PREFIX\",\"github_run_id\":\"$GITHUB_RUN_ID\"}")
          
          echo "SFN Execution ARN: $(echo $RESPONSE | jq -r '.executionArn')"
          echo "SFN_RESPONSE=$RESPONSE" >> $GITHUB_ENV

      - name: Wait for analysis completion
        if: failure()
        run: |
          # Poll Step Functions for completion (max 2 minutes)
          for i in {1..12}; do
            STATUS=$(aws stepfunctions describe-execution \
              --execution-arn $(echo $SFN_RESPONSE | jq -r '.executionArn') \
              --query 'status' --output text)
            
            if [ "$STATUS" = "SUCCEEDED" ]; then
              echo "Analysis completed successfully"
              break
            elif [ "$STATUS" = "FAILED" ]; then
              echo "Analysis failed"
              exit 1
            fi
            
            sleep 10
          done

      - name: Show remediation plan
        if: failure()
        run: |
          OUTPUT=$(aws stepfunctions describe-execution \
            --execution-arn $(echo $SFN_RESPONSE | jq -r '.executionArn') \
            --query 'output' --output text)
          
          echo "=== AIrtifacts ==="
          echo $OUTPUT | jq -r '.recommendations' || echo "No recommendations generated"
          echo "========================="
          
          # Create GitHub issue if critical failure
          if echo $OUTPUT | jq -e '.failure_type == "CRITICAL"'; then
            gh issue create \
              --title "Critical CI Failure in $GITHUB_SHA" \
              --body "$(echo $OUTPUT | jq -r '.recommendations')" \
              --label "bug,ci-failure"
          fi
